services:
  style-on:
    build:
      context: .
    ports:
      - "8090:8090"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_URI=r2dbc:postgresql://postgres:5432/${POSTGRES_DB}
      - FLYWAY_POSTGRES_URI=jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - ELASTICSEARCH_URIS=${ELASTICSEARCH_URIS}
      - ELASTICSEARCH_USERNAME=${ELASTICSEARCH_USERNAME}
      - ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_PASSWORD}
      - ELASTICSEARCH_INDEX_PRODUCT=${ELASTICSEARCH_INDEX_PRODUCT}
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:18.1
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_DB: '${POSTGRES_DB}'
    env_file:
      - .env
    volumes:
      - '.docker/postgres/data:/var/lib/postgresql'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 3s
      timeout: 5s
      retries: 5
